spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=moneyflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"