spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=moneyflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest